CREATE TABLE IF NOT EXISTS vote_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS vote_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voter VARCHAR(255) NOT NULL,
    vote_item_id INT NOT NULL,
    FOREIGN KEY (vote_item_id) REFERENCES vote_items(id)
);